### ISSUE TITLE
Not the same format

### ISSUE THREAD

**Issue by bolbol2017** [ineesalmeida/almeida-cv#1]
Hi,
Thank you for the nice template.
I followed the instructions but the results are not same: https://imgur.com/tAFFUx3
you can check it from here: https://bolbol2017.github.io/AhmedElsayed1/

P/s. this is my first experience with HTML, so I apologize if the problem concerning basic stuff

**Comment by ineesalmeida** [comment]
Hi!
I believe you didn't change the site's URL in the config file.
Your style sheet is pointing at "https://example.com/style.etc...", when it should be pointing at "https://bolbol2017.github.io/AhmedElsayed1/style.etc...".

You just need to update the `baseURL` parameter in the `config.toml` file.

Hope that helps!

**Comment by AlbertRapp** [comment]
Thanks for the hint with the baseURL. I had the same issue but it is working just fine now.

**Comment by takov751** [comment]
@ineesalmeida I have the same issue , even when i just try to do `hugo server -D` or `hugo server --disableFastRender`

even the syle.$hash.css is loaded,but still same result like @bolbol2017

**Comment by ineesalmeida** [comment]
Are there no errors when you run `hugo server -D`?
Can you try to inspect the HTML page and see if there are any errors in the console?

**Comment by takov751** [comment]
No errors. Even in browser style loaded , but same borked result

**Comment by ineesalmeida** [comment]
In bolbol2017's case, the issue was that they were missing the baseURL setting in their config file as I mentioned in a comment above.
If it's not the same issue, I'm not sure how I can help without more information

**Comment by takov751** [comment]
That's true thank you for the quick answer. My issue that I have Hugo extended installed , but when I follow your read me to reproduce the page even with your example site stuff . The page is broken as you have seen above. I tried with all forks as well . My only idea left that it might be an issue with the snap version of Hugo extended

**Comment by skylanskylion** [comment]
How do we add another sub tittle like for projects under experiences or change experience to say volunteer work

**Comment by skylanskylion** [comment]
Never mind, i figured it out, had to create new partial html and css files. Thanks for this repo :)

**Comment by skylanskylion** [comment]
> That's true thank you for the quick answer. My issue that I have Hugo extended installed , but when I follow your read me to reproduce the page even with your example site stuff . The page is broken as you have seen above. I tried with all forks as well . My only idea left that it might be an issue with the snap version of Hugo extended

I had the same issue while hosting on github pages. When you change the example.com to your github url it says it failed to create sass and css files and you wont be able to use >hugo to build the public folder either. what you need to do is leave it at that. Then run build and check if you have public folder. Now make a new docs/ folder in root directory and copy the public folder. Now everywhere where there's https://example.com/ replace them with relative links ./       
Now go to github pages and choose docs folder instead of root to host your site. It should work now. Here's mine https://skylanskylion.github.io/aakashcv/
