### ISSUE TITLE
LinkedIn social media icon

### ISSUE THREAD

**Issue by elkrause** [ineesalmeida/almeida-cv#12]
Hi! 

Great theme! :)

I have tried to add the LinkedIn social media icon from the Font Awesome font in content.yaml with 

```
Icon: fas fa-linkedin

```

But it doesn't work. Do I need to load the icon elsewhere?

Font Awesome supports it:
https://fontawesome.com/v5.15/icons/linkedin?style=brands

Thanks!

**Comment by benjaminjacobreji** [comment]
To get Github icon

`- Icon: fab fa-github`
