### ISSUE TITLE
Print to PDF only shows text

### ISSUE THREAD

**Issue by benjaminjacobreji** [ineesalmeida/almeida-cv#13]
Hi, 
I like this theme and want to use it but I am facing an issue.
I got the website to render properly online in the browser but when I try to print it I only get the text. Am I missing some config? 
I made sure to enable the Background Graphics option. I used Hugo Extended to build it. There were no errors during the build and `hugo server -D`

Website Link: [Example - CV](https://resume-gamma-pearl.vercel.app/)
Repo Link: [resume-pdf-test](https://github.com/benjaminjacobreji/resume-pdf-test)

This is what I get when  I try to print
![example cv print](https://user-images.githubusercontent.com/24478001/123432767-c1265100-d5db-11eb-8940-05dc56d68099.png)

What do I do to get the PrintToPDF working. This is a very useful theme for having an updated resume on the fly.

**Comment by b0ch3nski** [comment]
Hi,

I've included a fix for this in PR #14. For a quick workaround, you can edit theme code by yourself.

In `layouts/partials/head.html` find `media="screen"` and change to `media="screen,print"`

**Comment by ineesalmeida** [comment]
Hi @benjaminjacobreji,

As mentioned by b0ch3nski, this should be fixed in his PR which I just merged in. 
Let me know if it doesn't fix it!

**Comment by benjaminjacobreji** [comment]
Hi @ineesalmeida 
Yes, PR #14 has fixed my issue. Thank You @b0ch3nski.
Have a great day and thank you both for the help xD.

I'm closing this issue since it has been resolved with that PR.
