### ISSUE TITLE
Some customization issues

### ISSUE THREAD

**Issue by ygjose** [ineesalmeida/almeida-cv#7]
Hi Inês,

Thank you for the amazing CV template. Really like it. I'm doing some changes based on your template. But had some customization issues. Here is [my semi-finished cv](https://cv.gangyao.me). And if it's necessary, you can find [my git here](https://github.com/ygjose/cv).

When it's convenient, should you be so kind to help me out.🙏

To be clear, I have no prior knowledge about HTML and CSS... The only experience I have is the academic website I built on the top of another Hugo template. So bear with me if my questions does not make too much sense.

**❓1: How to add side section title for Contacts?** (something like the pic below)
![CleanShot 2021-01-25 at Safari浏览器CV | Gang Yao00 17 09](https://user-images.githubusercontent.com/37382523/105646932-06b2e680-5ea3-11eb-975b-0a25710ebc80.png)

💡**What I tried to do**: 

1. Made contact info independent from the ``BasicInfo`` section
```html
BasicInfo:
  FirstName: Gang
  LastName: Yao
  Photo: img/avatar.jpg

Contacts:
  - Icon: fas fa-envelope
    Info: gangyao[@]um[.]es
  - Icon: fas fa-globe
    Info: gangyao.me
  - Icon: fas fa-map-marker-alt
    Info: Spain
```

2. Copied the code from ``Skills`` partials, pasted into ``Contacts`` partials, and made some relevant changes
```html
{{ if .Site.Data.content.Contacts }}
<div class="sideSection">
    <div class="sideSection__heading">
        <h2 class="sideSection__title">{{ i18n "contact" }}</h2>
    </div>
    <div class="sideSection__content">
        <ul class="contact">
            {{ range .Site.Data.content.Contacts }}
            <li class="contact__item">
                <i class="{{ .Icon }}"></i><span>{{ .Info | safeHTML }}</span>
            </li>
            {{ end }}
        </ul>
    </div>
</div>
{{ end }}
```
❌ Results: fail to render the title

---
❓**2 How to change the title of Education section?** (Something like the pic below)
![CleanShot 2021-01-25 at Safari浏览器CV | Gang Yao00 36 03](https://user-images.githubusercontent.com/37382523/105647369-74f8a880-5ea5-11eb-8c1d-d9422971340a.png)

💡**What I tried to do**: I planed to build a customized section called "Publications", but I think it is difficult for me to do it, so I decided to make some changes on the top of the Education section in the original template: 

1. Simply changed the ``{{ i18n "education" }}`` to ``{{ i18n "publications" }}`` did not work;
2. I then used search and replace function to replace all ``education`` strings (including content.ymal, partials, and scss) with ``publications``. Didn't work either.

❌ **Results: my attempt failed again**

---
❓**3 How to space out two items in Education (or my customized Publications) section?**
💡**What I tried to do**: I would like to see there is some space between two items in ``Eduction`` section because the original one is quite compact (see the last screenshot).

1. I followed the ``__experience`` Component and add ``display: block`` to the ``__education`` Component (to the best of my knowledge...)
```css
.education {
    &__item {
        display: block;
        @include avoid-break;
    }
}
```
❌ **Results: my attempt failed again**

---
❓**4 How to change uppercase and font size in ``Experience`` section?**
💡**What I tried to do**: I wanted to change the uppercased job title to normal characters.

1. Find the CSS of job title in ``__experience`` Component
```css
&__position {
        text-transform: uppercase;
        font-size: 1.3rem;
        color: $color-grey-dark;
    }
```
2. Change ``text-transform: uppercase;`` to ``text-align: left;``
```css
    &__position {
        text-align: left;
        font-size: 1.3rem;
        color: $color-grey-dark;
    }
```
❌ **Results: my attempt failed again**

### Very sorry for the long post.

**Comment by ineesalmeida** [comment]
Hi!
Sorry for taking so long to reply, I hope this is still helpful!

**1.** I just gave that a try and it seems to work, so it might be something unrelated to the changes you made in the content file. Can you tell me what the error is?

**2.** You can create a translation file in the i18n folder (use the `en.toml` as an example), and then reference it in the `defaultContentLanguage`  in the config file

**3.** Not sure what you want in specific, but you can add a margin-bottom for example
```
.education {
    &__item {
        margin-bottom: 0.5rem; // or some other value, you can play around!
        @include avoid-break;
    }
}
```

**4.** That should work, I just gave it a try. I'm not sure what the issue might be. Is the title just still uppercase?

**Comment by ygjose** [comment]
Hi, 

No worries! I just tried again, and it didn't work. I guess the entire code is broken after my inexpert changes... I think I just leave it here. I might pick it up in the future when I have more knowledge about css and html.

Many thanks anyway!
