### ISSUE TITLE
Education tab getting cut while printing

### ISSUE THREAD

**Issue by skylanskylion** [ineesalmeida/almeida-cv#8]
I have built the theme and customised it. Even the localhost site looks fine but when i am printing it to export to pdf the last column gets cut. I have tried with different page sizes to same issue https://imgur.com/a/BcsL9xg
You can see that the site in localhost shows the education coloums but not while priting

**Comment by ineesalmeida** [comment]
Hi skylanskylion,

Have you tried changing the `pages` parameter in the `config.toml` file?

**Comment by skylanskylion** [comment]
Yes, that fixed it! Thanks so much
