### ISSUE TITLE
Chenge color of font

### ISSUE THREAD

**Issue by JaymeNeto** [ineesalmeida/almeida-cv#9]
I'm trying to change the color of the colorPrimary with is in #e3bfb8 but no matter how a chenge this variable the font keeps with the same color.

**Comment by ineesalmeida** [comment]
Hi @JaymeNeto,
You'll need to give me more information in order for me to help you.

So you can run your page and its well formatted with the default colors, then you try changing the color colorPrimary = "#e3bfb8" to another color in your `config.toml`, the color doesn't change?
